apiVersion: v1
kind: Service
metadata:
  name: capstone-project

spec:
  selector:
    app: capstone-project
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-project
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
        - name: capstone-project
          image: gavischneider/capstone-random-song
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
